name: ACA Runner Test

on:
  workflow_dispatch:

env:
  AZ_QUEUE_NAME: aca-runner-scaler
  AZ_STORAGE_ACCOUNT: acarunner

jobs:
  scale_runners_up:
    name: Scale Runners Up
    uses: ./.github/workflows/scale_runners_up.yml
    secrets: inherit
    with:
      queue_name: aca-runner-scaler
      storage_account: acarunner

  test_runners:
    name: Test the Runner
    needs: scale_runners_up
    runs-on: [self-hosted, ACA]

    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Display Terraform Version
        run: terraform --version

      - name: Display Azure-CLI Version
        run: az --version

      - name: Delay runner finish (2min)
        run: sleep 2m

  scale_runners_down:
    name: Scale Runners Down
    if: ${{ always() }}
    needs:
      - scale_runners_up
      - test_runners
    uses: ./.github/workflows/scale_runners_down.yml
    secrets: inherit
    with:
      queue_name: aca-runner-scaler
      storage_account: acarunner
      message_id: ${{ needs.scale_runners_up.outputs.message_id }}
      message_receipt: ${{ needs.scale_runners_up.outputs.message_receipt }}
