name: Scale ACA Runners Down

on:
  workflow_call:
    inputs:
      storage_account:
        type: string
        required: true
        description: 'The name of the storage account'
      queue_name:
        type: string
        required: true
        description: 'The name of the message queue'
      message_id:
        type: string
        required: true
        description: 'The ID of the message'
      message_receipt:
        type: string
        required: true
        description: 'The PopReceipt of the message'

jobs:
  scale_down:
    name: Scale Runners Down
    runs-on: [self-hosted, ACA]

    steps:
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p=${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: scale down self hosted
        run: |
          az storage message delete --auth-mode login --account-name ${{ inputs.storage_account }} -q ${{ inputs.queue_name }} --id "${{ inputs.message_id }}" --pop-receipt "${{ inputs.message_receipt }}"
